// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

// Import store internals
import { IStore } from "@latticexyz/store/src/IStore.sol";
import { StoreSwitch } from "@latticexyz/store/src/StoreSwitch.sol";
import { StoreCore } from "@latticexyz/store/src/StoreCore.sol";
import { Bytes } from "@latticexyz/store/src/Bytes.sol";
import { Memory } from "@latticexyz/store/src/Memory.sol";
import { SliceLib } from "@latticexyz/store/src/Slice.sol";
import { EncodeArray } from "@latticexyz/store/src/tightcoder/EncodeArray.sol";
import { FieldLayout } from "@latticexyz/store/src/FieldLayout.sol";
import { Schema } from "@latticexyz/store/src/Schema.sol";
import { EncodedLengths, EncodedLengthsLib } from "@latticexyz/store/src/EncodedLengths.sol";
import { ResourceId } from "@latticexyz/store/src/ResourceId.sol";

struct RoundLogData {
  uint32 harvest0;
  uint32 harvest1;
  uint32 harvest2;
  uint32 harvest3;
  uint32 harvest4;
}

library RoundLog {
  // Hex below is the result of `WorldResourceIdLib.encode({ namespace: "app", name: "RoundLog", typeId: RESOURCE_TABLE });`
  ResourceId constant _tableId = ResourceId.wrap(0x74626170700000000000000000000000526f756e644c6f670000000000000000);

  FieldLayout constant _fieldLayout =
    FieldLayout.wrap(0x0014050004040404040000000000000000000000000000000000000000000000);

  // Hex-encoded key schema of (uint32)
  Schema constant _keySchema = Schema.wrap(0x0004010003000000000000000000000000000000000000000000000000000000);
  // Hex-encoded value schema of (uint32, uint32, uint32, uint32, uint32)
  Schema constant _valueSchema = Schema.wrap(0x0014050003030303030000000000000000000000000000000000000000000000);

  /**
   * @notice Get the table's key field names.
   * @return keyNames An array of strings with the names of key fields.
   */
  function getKeyNames() internal pure returns (string[] memory keyNames) {
    keyNames = new string[](1);
    keyNames[0] = "round";
  }

  /**
   * @notice Get the table's value field names.
   * @return fieldNames An array of strings with the names of value fields.
   */
  function getFieldNames() internal pure returns (string[] memory fieldNames) {
    fieldNames = new string[](5);
    fieldNames[0] = "harvest0";
    fieldNames[1] = "harvest1";
    fieldNames[2] = "harvest2";
    fieldNames[3] = "harvest3";
    fieldNames[4] = "harvest4";
  }

  /**
   * @notice Register the table with its config.
   */
  function register() internal {
    StoreSwitch.registerTable(_tableId, _fieldLayout, _keySchema, _valueSchema, getKeyNames(), getFieldNames());
  }

  /**
   * @notice Register the table with its config.
   */
  function _register() internal {
    StoreCore.registerTable(_tableId, _fieldLayout, _keySchema, _valueSchema, getKeyNames(), getFieldNames());
  }

  /**
   * @notice Get harvest0.
   */
  function getHarvest0(uint32 round) internal view returns (uint32 harvest0) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(round));

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 0, _fieldLayout);
    return (uint32(bytes4(_blob)));
  }

  /**
   * @notice Get harvest0.
   */
  function _getHarvest0(uint32 round) internal view returns (uint32 harvest0) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(round));

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 0, _fieldLayout);
    return (uint32(bytes4(_blob)));
  }

  /**
   * @notice Set harvest0.
   */
  function setHarvest0(uint32 round, uint32 harvest0) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(round));

    StoreSwitch.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked((harvest0)), _fieldLayout);
  }

  /**
   * @notice Set harvest0.
   */
  function _setHarvest0(uint32 round, uint32 harvest0) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(round));

    StoreCore.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked((harvest0)), _fieldLayout);
  }

  /**
   * @notice Get harvest1.
   */
  function getHarvest1(uint32 round) internal view returns (uint32 harvest1) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(round));

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 1, _fieldLayout);
    return (uint32(bytes4(_blob)));
  }

  /**
   * @notice Get harvest1.
   */
  function _getHarvest1(uint32 round) internal view returns (uint32 harvest1) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(round));

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 1, _fieldLayout);
    return (uint32(bytes4(_blob)));
  }

  /**
   * @notice Set harvest1.
   */
  function setHarvest1(uint32 round, uint32 harvest1) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(round));

    StoreSwitch.setStaticField(_tableId, _keyTuple, 1, abi.encodePacked((harvest1)), _fieldLayout);
  }

  /**
   * @notice Set harvest1.
   */
  function _setHarvest1(uint32 round, uint32 harvest1) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(round));

    StoreCore.setStaticField(_tableId, _keyTuple, 1, abi.encodePacked((harvest1)), _fieldLayout);
  }

  /**
   * @notice Get harvest2.
   */
  function getHarvest2(uint32 round) internal view returns (uint32 harvest2) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(round));

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 2, _fieldLayout);
    return (uint32(bytes4(_blob)));
  }

  /**
   * @notice Get harvest2.
   */
  function _getHarvest2(uint32 round) internal view returns (uint32 harvest2) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(round));

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 2, _fieldLayout);
    return (uint32(bytes4(_blob)));
  }

  /**
   * @notice Set harvest2.
   */
  function setHarvest2(uint32 round, uint32 harvest2) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(round));

    StoreSwitch.setStaticField(_tableId, _keyTuple, 2, abi.encodePacked((harvest2)), _fieldLayout);
  }

  /**
   * @notice Set harvest2.
   */
  function _setHarvest2(uint32 round, uint32 harvest2) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(round));

    StoreCore.setStaticField(_tableId, _keyTuple, 2, abi.encodePacked((harvest2)), _fieldLayout);
  }

  /**
   * @notice Get harvest3.
   */
  function getHarvest3(uint32 round) internal view returns (uint32 harvest3) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(round));

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 3, _fieldLayout);
    return (uint32(bytes4(_blob)));
  }

  /**
   * @notice Get harvest3.
   */
  function _getHarvest3(uint32 round) internal view returns (uint32 harvest3) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(round));

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 3, _fieldLayout);
    return (uint32(bytes4(_blob)));
  }

  /**
   * @notice Set harvest3.
   */
  function setHarvest3(uint32 round, uint32 harvest3) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(round));

    StoreSwitch.setStaticField(_tableId, _keyTuple, 3, abi.encodePacked((harvest3)), _fieldLayout);
  }

  /**
   * @notice Set harvest3.
   */
  function _setHarvest3(uint32 round, uint32 harvest3) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(round));

    StoreCore.setStaticField(_tableId, _keyTuple, 3, abi.encodePacked((harvest3)), _fieldLayout);
  }

  /**
   * @notice Get harvest4.
   */
  function getHarvest4(uint32 round) internal view returns (uint32 harvest4) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(round));

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 4, _fieldLayout);
    return (uint32(bytes4(_blob)));
  }

  /**
   * @notice Get harvest4.
   */
  function _getHarvest4(uint32 round) internal view returns (uint32 harvest4) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(round));

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 4, _fieldLayout);
    return (uint32(bytes4(_blob)));
  }

  /**
   * @notice Set harvest4.
   */
  function setHarvest4(uint32 round, uint32 harvest4) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(round));

    StoreSwitch.setStaticField(_tableId, _keyTuple, 4, abi.encodePacked((harvest4)), _fieldLayout);
  }

  /**
   * @notice Set harvest4.
   */
  function _setHarvest4(uint32 round, uint32 harvest4) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(round));

    StoreCore.setStaticField(_tableId, _keyTuple, 4, abi.encodePacked((harvest4)), _fieldLayout);
  }

  /**
   * @notice Get the full data.
   */
  function get(uint32 round) internal view returns (RoundLogData memory _table) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(round));

    (bytes memory _staticData, EncodedLengths _encodedLengths, bytes memory _dynamicData) = StoreSwitch.getRecord(
      _tableId,
      _keyTuple,
      _fieldLayout
    );
    return decode(_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Get the full data.
   */
  function _get(uint32 round) internal view returns (RoundLogData memory _table) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(round));

    (bytes memory _staticData, EncodedLengths _encodedLengths, bytes memory _dynamicData) = StoreCore.getRecord(
      _tableId,
      _keyTuple,
      _fieldLayout
    );
    return decode(_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using individual values.
   */
  function set(
    uint32 round,
    uint32 harvest0,
    uint32 harvest1,
    uint32 harvest2,
    uint32 harvest3,
    uint32 harvest4
  ) internal {
    bytes memory _staticData = encodeStatic(harvest0, harvest1, harvest2, harvest3, harvest4);

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(round));

    StoreSwitch.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using individual values.
   */
  function _set(
    uint32 round,
    uint32 harvest0,
    uint32 harvest1,
    uint32 harvest2,
    uint32 harvest3,
    uint32 harvest4
  ) internal {
    bytes memory _staticData = encodeStatic(harvest0, harvest1, harvest2, harvest3, harvest4);

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(round));

    StoreCore.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData, _fieldLayout);
  }

  /**
   * @notice Set the full data using the data struct.
   */
  function set(uint32 round, RoundLogData memory _table) internal {
    bytes memory _staticData = encodeStatic(
      _table.harvest0,
      _table.harvest1,
      _table.harvest2,
      _table.harvest3,
      _table.harvest4
    );

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(round));

    StoreSwitch.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using the data struct.
   */
  function _set(uint32 round, RoundLogData memory _table) internal {
    bytes memory _staticData = encodeStatic(
      _table.harvest0,
      _table.harvest1,
      _table.harvest2,
      _table.harvest3,
      _table.harvest4
    );

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(round));

    StoreCore.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData, _fieldLayout);
  }

  /**
   * @notice Decode the tightly packed blob of static data using this table's field layout.
   */
  function decodeStatic(
    bytes memory _blob
  ) internal pure returns (uint32 harvest0, uint32 harvest1, uint32 harvest2, uint32 harvest3, uint32 harvest4) {
    harvest0 = (uint32(Bytes.getBytes4(_blob, 0)));

    harvest1 = (uint32(Bytes.getBytes4(_blob, 4)));

    harvest2 = (uint32(Bytes.getBytes4(_blob, 8)));

    harvest3 = (uint32(Bytes.getBytes4(_blob, 12)));

    harvest4 = (uint32(Bytes.getBytes4(_blob, 16)));
  }

  /**
   * @notice Decode the tightly packed blobs using this table's field layout.
   * @param _staticData Tightly packed static fields.
   *
   *
   */
  function decode(
    bytes memory _staticData,
    EncodedLengths,
    bytes memory
  ) internal pure returns (RoundLogData memory _table) {
    (_table.harvest0, _table.harvest1, _table.harvest2, _table.harvest3, _table.harvest4) = decodeStatic(_staticData);
  }

  /**
   * @notice Delete all data for given keys.
   */
  function deleteRecord(uint32 round) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(round));

    StoreSwitch.deleteRecord(_tableId, _keyTuple);
  }

  /**
   * @notice Delete all data for given keys.
   */
  function _deleteRecord(uint32 round) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(round));

    StoreCore.deleteRecord(_tableId, _keyTuple, _fieldLayout);
  }

  /**
   * @notice Tightly pack static (fixed length) data using this table's schema.
   * @return The static data, encoded into a sequence of bytes.
   */
  function encodeStatic(
    uint32 harvest0,
    uint32 harvest1,
    uint32 harvest2,
    uint32 harvest3,
    uint32 harvest4
  ) internal pure returns (bytes memory) {
    return abi.encodePacked(harvest0, harvest1, harvest2, harvest3, harvest4);
  }

  /**
   * @notice Encode all of a record's fields.
   * @return The static (fixed length) data, encoded into a sequence of bytes.
   * @return The lengths of the dynamic fields (packed into a single bytes32 value).
   * @return The dynamic (variable length) data, encoded into a sequence of bytes.
   */
  function encode(
    uint32 harvest0,
    uint32 harvest1,
    uint32 harvest2,
    uint32 harvest3,
    uint32 harvest4
  ) internal pure returns (bytes memory, EncodedLengths, bytes memory) {
    bytes memory _staticData = encodeStatic(harvest0, harvest1, harvest2, harvest3, harvest4);

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    return (_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Encode keys as a bytes32 array using this table's field layout.
   */
  function encodeKeyTuple(uint32 round) internal pure returns (bytes32[] memory) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(round));

    return _keyTuple;
  }
}
