// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { FisheryPool, FisheryPoolData } from "./tables/FisheryPool.sol";
import { AgentProfile } from "./tables/AgentProfile.sol";
import { Inventory } from "./tables/Inventory.sol";
import { RoundLog, RoundLogData } from "./tables/RoundLog.sol";
