// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IFisherySystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IFisherySystem {
  function app__initFishery(bool hardRule) external returns (uint32 stock);

  function app__harvest(bytes32 agentId, uint8 requested) external returns (uint8 executed);
}
